/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connectionDB.koneksi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    
    public boolean isUsernameAvailable(String username) {
        String sql = "SELECT COUNT(*) FROM tbuser WHERE username = ?";
        try (PreparedStatement stat = conn.prepareStatement(sql);) {
            stat.setString(1, username);
            ResultSet resultSet = stat.executeQuery();
            resultSet.next();
            int count = resultSet.getInt(1);
            return count == 0;

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
    
    protected void kosong(){
        tnamalengkap.setText("");
        tregisuser.setText("");
        tregispass.setText("");
        tregisrepass.setText("");
    }
    
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        panelheader = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelmain = new javax.swing.JPanel();
        panellogin = new javax.swing.JPanel();
        labelnama = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bmasuk = new javax.swing.JButton();
        bregis = new javax.swing.JButton();
        labelnama1 = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        panelregister = new javax.swing.JPanel();
        tregispass = new javax.swing.JPasswordField();
        tnamalengkap = new javax.swing.JTextField();
        labelnama4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelnama6 = new javax.swing.JLabel();
        tregisuser = new javax.swing.JTextField();
        labelnama8 = new javax.swing.JLabel();
        tregisrepass = new javax.swing.JPasswordField();
        labelnama9 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        bbersih = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelgambar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panelutama.setBackground(new java.awt.Color(255, 153, 153));

        panelheader.setBackground(new java.awt.Color(153, 51, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/logohanna-removebg-preview.png"))); // NOI18N

        judul1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul1.setForeground(new java.awt.Color(255, 255, 255));
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul1.setText("POSYANDU ANYELIR");

        judul2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        judul2.setForeground(new java.awt.Color(255, 255, 255));
        judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul2.setText("SEKRETARIAT : JL. DANAU TEMPE RAYA RW 06 KELURAHAN ABADIJAYA KECAMATAN SUKMAJAYA");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelheaderLayout.createSequentialGroup()
                        .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelheaderLayout.createSequentialGroup()
                        .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))))
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelheaderLayout.createSequentialGroup()
                        .addGroup(panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelheaderLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelmain.setBackground(new java.awt.Color(102, 255, 204));
        panelmain.setLayout(new java.awt.CardLayout());

        panellogin.setBackground(new java.awt.Color(255, 153, 153));

        labelnama.setBackground(new java.awt.Color(255, 255, 255));
        labelnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelnama.setText("USERNAME");
        labelnama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Silahkan Masuk");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        bmasuk.setBackground(new java.awt.Color(0, 0, 204));
        bmasuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bmasuk.setForeground(new java.awt.Color(255, 255, 255));
        bmasuk.setText("Masuk");
        bmasuk.setContentAreaFilled(false);
        bmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bmasuk.setOpaque(true);
        bmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bmasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bmasukMouseExited(evt);
            }
        });
        bmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmasukActionPerformed(evt);
            }
        });

        bregis.setBackground(new java.awt.Color(0, 0, 204));
        bregis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bregis.setForeground(new java.awt.Color(255, 255, 255));
        bregis.setText("Register");
        bregis.setContentAreaFilled(false);
        bregis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bregis.setOpaque(true);
        bregis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bregisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bregisMouseExited(evt);
            }
        });
        bregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisActionPerformed(evt);
            }
        });

        labelnama1.setBackground(new java.awt.Color(255, 255, 255));
        labelnama1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnama1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelnama1.setText("PASSWORD");
        labelnama1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelloginLayout = new javax.swing.GroupLayout(panellogin);
        panellogin.setLayout(panelloginLayout);
        panelloginLayout.setHorizontalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tusername))
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addComponent(bmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(bregis, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelloginLayout.createSequentialGroup()
                        .addComponent(labelnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpassword)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        panelloginLayout.setVerticalGroup(
            panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelloginLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(panelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bregis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        panelmain.add(panellogin, "card2");

        panelregister.setBackground(new java.awt.Color(255, 153, 153));

        tregispass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tregispass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tregispassKeyPressed(evt);
            }
        });

        tnamalengkap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tnamalengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamalengkapActionPerformed(evt);
            }
        });

        labelnama4.setBackground(new java.awt.Color(255, 255, 255));
        labelnama4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnama4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelnama4.setText("NAMA LENGKAP");
        labelnama4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrasi");

        labelnama6.setBackground(new java.awt.Color(255, 255, 255));
        labelnama6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnama6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelnama6.setText("USERNAME");
        labelnama6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tregisuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tregisuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tregisuserActionPerformed(evt);
            }
        });

        labelnama8.setBackground(new java.awt.Color(255, 255, 255));
        labelnama8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnama8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelnama8.setText("PASSWORD");
        labelnama8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tregisrepass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tregisrepass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tregisrepassKeyPressed(evt);
            }
        });

        labelnama9.setBackground(new java.awt.Color(255, 255, 255));
        labelnama9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnama9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelnama9.setText("ULANGI PASSWORD");
        labelnama9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bsimpan.setBackground(new java.awt.Color(0, 0, 204));
        bsimpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.setContentAreaFilled(false);
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.setOpaque(true);
        bsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bsimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bsimpanMouseExited(evt);
            }
        });
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bbersih.setBackground(new java.awt.Color(0, 0, 204));
        bbersih.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bbersih.setForeground(new java.awt.Color(255, 255, 255));
        bbersih.setText("Bersihkan");
        bbersih.setContentAreaFilled(false);
        bbersih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bbersih.setOpaque(true);
        bbersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbersihMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbersihMouseExited(evt);
            }
        });
        bbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelregisterLayout = new javax.swing.GroupLayout(panelregister);
        panelregister.setLayout(panelregisterLayout);
        panelregisterLayout.setHorizontalGroup(
            panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelregisterLayout.createSequentialGroup()
                .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelregisterLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelnama4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelnama6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelnama8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelnama9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelregisterLayout.createSequentialGroup()
                                .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bbersih, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tnamalengkap)
                            .addComponent(tregisuser, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tregispass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tregisrepass, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelregisterLayout.createSequentialGroup()
                        .addContainerGap(75, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        panelregisterLayout.setVerticalGroup(
            panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelregisterLayout.createSequentialGroup()
                .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelregisterLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelregisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(23, 23, 23)
                .addComponent(labelnama4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnamalengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelnama6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tregisuser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelnama8)
                .addGap(4, 4, 4)
                .addComponent(tregispass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelnama9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tregisrepass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbersih, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelmain.add(panelregister, "card3");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/posyandu.jpg"))); // NOI18N

        javax.swing.GroupLayout panelgambarLayout = new javax.swing.GroupLayout(panelgambar);
        panelgambar.setLayout(panelgambarLayout);
        panelgambarLayout.setHorizontalGroup(
            panelgambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelgambarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        panelgambarLayout.setVerticalGroup(
            panelgambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelgambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panelheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addComponent(panelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelgambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tusernameActionPerformed

    private void bmasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmasukMouseEntered
        bmasuk.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_bmasukMouseEntered

    private void bmasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmasukMouseExited
        bmasuk.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_bmasukMouseExited

    private void bmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmasukActionPerformed
        String level ="";
        try {
            tusername.requestFocus();
            java.sql.Statement stat = conn.createStatement();
            ResultSet result=stat.executeQuery ("SELECT * FROM tbuser WHERE "
                + "username='" +tusername.getText()+"'");
            if (result.next()) {
                if (tpassword.getText().equals(result.getString("password"))){
                    JOptionPane.showMessageDialog(rootPane, "Selamat Datang "+tusername.getText());
                    mainmenu mm = new mainmenu();
                    mm.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane,"Password Salah");
                    tpassword.setText("");
                    tusername.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "User Tidak Ditemukan");
                tusername.setText("");
                tpassword.setText("");
                tusername.requestFocus();
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }//GEN-LAST:event_bmasukActionPerformed

    private void bregisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bregisMouseEntered
        bregis.setBackground(Color.red);
    }//GEN-LAST:event_bregisMouseEntered

    private void bregisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bregisMouseExited
        bregis.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_bregisMouseExited

    private void bregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisActionPerformed
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panelregister);
        panelmain.repaint();
        panelmain.revalidate();
        bregis.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_bregisActionPerformed

    private void tpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpasswordKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            bmasukActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), "Key Press Login"));
        }
    }//GEN-LAST:event_tpasswordKeyPressed

    private void tregispassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tregispassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tregispassKeyPressed

    private void tnamalengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamalengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamalengkapActionPerformed

    private void tregisuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tregisuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tregisuserActionPerformed

    private void tregisrepassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tregisrepassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tregisrepassKeyPressed

    private void bsimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsimpanMouseEntered
        bsimpan.setBackground(new Color(0,255,0));
    }//GEN-LAST:event_bsimpanMouseEntered

    private void bsimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsimpanMouseExited
        bsimpan.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_bsimpanMouseExited

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        
        String sql = "insert into tbuser values (?,?,?,?)";
        try{
            if (isUsernameAvailable(tregisuser.getText())) {
                if (tnamalengkap.getText().isEmpty() || tregisuser.getText().isEmpty() || tregispass.getText().isEmpty()
                    || tregisrepass.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Semua data harus terisi", "Notice !!!", JOptionPane.WARNING_MESSAGE);
                } else {
                    if (tregispass.getText().equals(tregisrepass.getText())) {
                        PreparedStatement stat = conn.prepareStatement(sql);
                        stat.setString(1, tnamalengkap.getText());
                        stat.setString(2, tregisuser.getText());
                        stat.setString(3, tregispass.getText());
                        stat.setString(4, tregisrepass.getText());
                        stat.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                        kosong();
                        tnamalengkap.requestFocus();
                        
                        panelmain.removeAll();
                        panelmain.repaint();
                        panelmain.revalidate();
                        //add panel
                        panelmain.add(panellogin);
                        panelmain.repaint();
                        panelmain.revalidate();
                    }else{
                        JOptionPane.showMessageDialog(null, "Password tidak sama. Harap periksa kembali.", "Notice !!!", JOptionPane.WARNING_MESSAGE);
                        tregispass.setText("");
                        tregisrepass.setText("");
                    }
                }
            }else {
                JOptionPane.showMessageDialog(null, "Username sudah digunakan", "Notice !!!", JOptionPane.WARNING_MESSAGE);
                tregisuser.setText("");
            }
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbersihMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbersihMouseEntered
        bbersih.setBackground(Color.red);
    }//GEN-LAST:event_bbersihMouseEntered

    private void bbersihMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbersihMouseExited
        bbersih.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_bbersihMouseExited

    private void bbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihActionPerformed
        kosong();
    }//GEN-LAST:event_bbersihActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panellogin);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.black);
    }//GEN-LAST:event_jLabel5MouseExited
    private int xMouse,yMouse;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbersih;
    private javax.swing.JButton bmasuk;
    private javax.swing.JButton bregis;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnama1;
    private javax.swing.JLabel labelnama4;
    private javax.swing.JLabel labelnama6;
    private javax.swing.JLabel labelnama8;
    private javax.swing.JLabel labelnama9;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelgambar;
    private javax.swing.JPanel panelheader;
    private javax.swing.JPanel panellogin;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel panelregister;
    private javax.swing.JPanel panelutama;
    private javax.swing.JTextField tnamalengkap;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JPasswordField tregispass;
    private javax.swing.JPasswordField tregisrepass;
    private javax.swing.JTextField tregisuser;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
